### ISSUE TITLE
Can't use it on the  x86 platform

### ISSUE THREAD

**Issue by ghost** [andrew-gresyk/HFSM#10]
I cant' compile codes of example  well by vs 17 on the windows 10.
These are some error information as following.

main.cpp
1>d:\myfile\hfsm-master\include\hfsm\detail\wrap.hpp(49): error C2338:
1>d:\myfile\hfsm-master\include\hfsm\detail\type_info.hpp(14): note: 参见对正在编译的 类 模板 实例化 "hfsm::detail::Wrap<std::type_index>" 的引用
1>streetlight.cpp
1>d:\myfile\hfsm-master\include\hfsm\detail\wrap.hpp(49): error C2338:
1>d:\myfile\hfsm-master\include\hfsm\detail\type_info.hpp(14): note: 参见对正在编译的 类 模板 实例化 "hfsm::detail::Wrap<std::type_index>" 的引用
1>正在生成代码...
1>已完成生成项目“HFSM-vs.vcxproj”的操作 - 失败。

**Comment by andrew-gresyk** [comment]
Thanks for reporting.
32bit VS build fixed in [43ab482](https://github.com/andrew-gresyk/HFSM/commit/43ab48234d706371a445a3bc971276d2f9381a5a)
