### ISSUE TITLE
More Complete Examples

### ISSUE THREAD

**Issue by bryceschober** [andrew-gresyk/HFSM#11]
I ran across your library and talks, but I'm still having a hard time connecting the dots. It would be nice if some of the examples from your talks were available as more fully worked examples... and some docs might be nice. ;-)

**Comment by andrew-gresyk** [comment]
Yeah, I'll add a couple of simple examples to demonstrate basic usage this week.

If you have any specific ideas as to what the kind of examples that would help (simple - e.g. a classic streetlight, or more complex) - feel free to post here.

Doc update is in progress, meanwhile there's an [automatic structure visualization](https://andrew-gresyk.github.io/features/2018/01/15/hfsm-magic.html) announcement that hasn't made it into the main docs.

My guess is the docs need more prose, correct?

**Comment by bryceschober** [comment]
It would be really good to have a complete working example of the player character state machine that you went through in the [April 2017 meetup](https://andrew-gresyk.github.io/presentations/2017/04/11/hfsm-for-videogames.html), since your other talks' slides are much more abbreviated.

Also, it might be good to link to [andrew-gresyk.github.io](https://andrew-gresyk.github.io) from your profile and to your talks' pages from this project.

**Comment by andrew-gresyk** [comment]
Player character state machine from April '17 was written in the predecessor to HFSM in C#/Unity.

I'll add a couple simple examples demonstrating library features, and maybe something more complex (similar to the player character from the Jan '18 talk) to showcase hierarchical composition.

**Comment by andrew-gresyk** [comment]
Are you looking to use HFSM in a project of yours?

**Comment by bryceschober** [comment]
Looking to at least try it out in a bare-metal embedded environment.

**Comment by andrew-gresyk** [comment]
[examples](../tree/master/examples) added, more on the way.
