### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by bryceschober** [andrew-gresyk/HFSM#12]
Is there any documentation beyond that in the README.md?

1. It's not clear to me what is the intended API surface area for a non-advanced state machine usage.
2. It's not clear to me what exactly is intended with the `substitute()` method.
3. You kinda introduce the concept of a timed state in your April 2017 presentation and in the `test/main.cpp` without any built-in support or introductory documentation how to extend states properly. This would be helped by a more-fully worked player character example via issue #11, of course... but I wonder if perhaps some of those extensions are worth providing in the library.

**Comment by andrew-gresyk** [comment]
OK, I'll add more detailed tutorial, together with examples it should help.
Substitute, injections aren't covered in readme, they deserve dedicated pages.

**Comment by andrew-gresyk** [comment]
FYI, I'm reworking the docs, if you want to check the new README and [tutorial](https://github.com/andrew-gresyk/HFSM/blob/master/doc/tutorial.md).
`substitute()` page is coming soon.

**Comment by bryceschober** [comment]
FYI, the link to the example in the tutorial is currently broken.

**Comment by bryceschober** [comment]
Some feedback on the design this time, after reading through the tutorial and example and actually mostly understanding it this time:

I found myself wishing that the state types were more explicit as I read through their definitions. It seems that most states would be designed to always fit into the same kind of slot in the hierarchy, and it would be helpful if their declarations were more explicit.

If a state is destined to be the head or a non-head sub-state, then it would be helpful to declare it as such, and it would enable compile-time checking of the eventual state machine construction. Same goes for differentiation between region types: if a state is destined for a composite vs. an orthogonal region, then it would be helpful to declare it as such and check the construction at compile time.

Even if the implementation of the state is identical, they could still be "strong types" that are "tagged" for more readably and verifiably different uses.

**Comment by andrew-gresyk** [comment]
I see.
How would you suggest to implement this?

**Comment by andrew-gresyk** [comment]
All existing docs were moved to [Wiki](../../wiki), more is coming, see sidebar for the planned list of topics.
