### ISSUE TITLE
Support passing action data to States

### ISSUE THREAD

**Issue by kgreenek** [andrew-gresyk/HFSM#7]
I often need to transition from state A to state B in response to an action. You do this by implementing the `react()` method on state A for the given action. However, often the information in the action is needed by state B. Currently, the way to accomplish this is to pass the data to state B is to set a member variable in the Context object.

```c++
struct SaveAction {
  std::string file_to_save;
}

struct IdleState : M::Bare {
  void react(const SaveAction &action, M::Control &control, Context &context) {
    context.file_to_save = action.file_to_save;
    control.changeTo<SavingState>();
  }
}

struct SavingState : M::Bare {
  void enter(Context &context) {
    // It would be nice to have a better way of accessing file_to_save.
    saveFile(context.file_to_save);
  }
}
```

This works, but I'm finding that I have a lot of these member variables in my Context that are specific to one state transitioning to another. It would be nice if my IdleState above had some way of passing the file_to_save (or the SaveAction) to the SavingState.

Is there a better way for me to handle this situation? Perhaps I could think differently about how the states are structured?

**Comment by andrew-gresyk** [comment]
Yeah, I'd normally put all data shared between states into context. Often I'd create sub-structs within for clarity.

What kind of interface are you thinking of for the receiving states to access the data being sent?

**Comment by kgreenek** [comment]
I'm not sure tbh! This is more of an open-ended feature request.

Brainstorming:

At a high-level, some states are going to _always_ require certain information on enter. That could be enforced formally in the API by changing the changeTo<>() method to accept some argument.

For example, in my example above, the `SavingState` _always_ needs a `file_to_save`. So perhaps its `enter` method could look like this somehow:

```c++
  void enter(Context &context, std::string file_to_save) {
    saveFile(file_to_save);
  }
```

And when you change to that state, you HAVE to call it with the file, like this:

```c++
control.changeTo<SavingState>("some_file.txt");
```

**Comment by andrew-gresyk** [comment]
Don't forget that in a hierarchy you'll end up with multiple states being activated.

**Comment by kgreenek** [comment]
That would clean up the Context implementations quite a bit, and the compiler would formally enforce that required information is actually provided correctly. I imagine this would prevent lots of subtle bugs that arise from forgetting to set up the context before transitioning to a state.

**Comment by kgreenek** [comment]
Ah true... if a leaf state requires some arg, that value would have to somehow be passed through when changing states to its parent.. hmm, that would get hairy

**Comment by andrew-gresyk** [comment]
Indeed..
Also, the 'parametrized' state might get activated because of its parent (or child) state activation.

**Comment by kgreenek** [comment]
Another possible idea would be to dispatch a message to the state before the call to `changeTo`. And when a state is entered, it can access the data via a queue / stack.

**Comment by andrew-gresyk** [comment]
BTW, all transitions are processed during `Root::update()`.
So strictly speaking, it doesn't matter, before or after `changeTo()`, but before `update()`.

I'm tempted to say this message queue might be slightly outside the responsibilities of the state machine, whose primary responsibility is to drive state transitions.

This message queue can exist inside context, and source state could push a message (protected by some key?) in, and the destination state might pop it (using the same key?).

**Comment by andrew-gresyk** [comment]
That said, if you can provide a more detailed design, I'd be happy to consider it for integration.

For that I'd need a message queue, and a high-level design of the changes to the interface of the library.
E.g. how would you define the types of messages a state can send/receive, etc.

**Comment by kgreenek** [comment]
Definitely is a "nice to have" kind of feature. Would be helpful, but isn't really needed to make something that works.

Given that the state machine for my current use-case is super simple, I'll probably just set fields in the Context.

If it starts to get unwieldy, then I'll build some message-passing utility for states in my project. And then if it makes sense to merge upstream, then I'll revisit this thread :). My gut feeling is that it would be tricky to make it part of the HFSM library without introducing dynamic allocations, or making the interface clunky.

Anyways, I appreciate the discussion. Feel free to close this issue, or keep it open if you think it's worth tracking.

**Comment by andrew-gresyk** [comment]
Exactly, you're absolutely right about dynamic allocations.
To avoid those - some kind of typed memory pool can be used which is likely to result in memory over-reservation.

I need to sleep on this (multiple times), maybe some clever solution will present itself :D
