### ISSUE TITLE
Exception handling from react() methods

### ISSUE THREAD

**Issue by kgreenek** [andrew-gresyk/HFSM#9]
Question:

Is there a best-practice for indicating that a certain action is not allowed?

My intuition is to throw an exception from the `react()` method if that action is not allowed for a particular state. Will that cause problems?

**Comment by andrew-gresyk** [comment]
There's no preference really.

Can that be expressed by the state not implementing `react()`?

**Comment by kgreenek** [comment]
Well, all I really need is for my calling code needs to know that the action failed because it isn't allowed in the current state.

So, for example, I would like to do:
```c++
try {
  machine.react(MyAction{});
} catch (...) {
  std::cout << "Action not allowed" << std::endl;
}
```

**Comment by kgreenek** [comment]
If I throw an exception in my state's react implementation, I jut want to confirm that that won't mess up any internal HFSM stuff in the state machine.

**Comment by kgreenek** [comment]
I'm also finding something weird if I have multiple actions. In a state, if I implement one of the `react` methods, then I have to implement all of them or it doesn't compile. Is there a way to have a default react handler for any actions without a specific implementation? Then I could just have that default react method throw an exception.

**Comment by andrew-gresyk** [comment]
Oh I see.
I'd use a bool variable in Context for that, but I don't normally use exceptions for control flow in games.

Throwing an exception in `react()` should be safe. Any transitions initiated in any of the `react()` functions across the entire state machine during that call to `machine.react()` will be ignored. That's not a 'normal' operation, but shouldn't leave the state machine in a bad state.

99% sure about that, but I'd not recommend that :)

Throwing an exception in `enter()` or `leave()` would be 100% a bad idea and would cause the state machine to end up in an unrecoverable state.

What exactly do you mean by:
> I have to implement all of them or it doesn't compile

?

Do you have a code snippet I can test?
